INDEX_NAMES = [
    'Academic year',
    'Academic Year',
    'Activity',
    'age_detailed',
    'age_group',
    'age_summary_with_unknowns',
    'age_youth_adult',
    'apprenticeships_or_further_education',
    'CAH level marker',
    'CAH level subject',
    'Category marker',
    'Category',
    'characteristic_group',
    'characteristic_type',
    'Characteristic',
    'cohort_level',
    'Country of HE provider',
    'Country of provider',
    'Data type',
    'date',
    'Domicile',
    'employment_status',
    'ethnicity_group',
    'ethnicity',
    'First year marker',
    'geography_code',
    'geography_name',
    'HE provider',
    'Institution group',
    'institution_type',
    'Institution',
    'Interim study',
    'la_name',
    'Level of qualification obtained',
    'Level of study',
    'level_or_type',
    'lldd',
    'Mode of former study',
    'Mode of study',
    'new_la_code',
    'notional_nvq_level',
    'prior_attainment_group',
    'Provider name',
    'Qualification level',
    'Qualification',
    'Region of HE provider',
    'school_type_group',
    'sex',
    'Sex',
    'ssa_t1_desc',
    'ssa_t1',
    'ssa_t2',
    'start_age',
    'Student characteristic',
    'Subject area of degree',
    'Subject of study marker',
    'Subject of study',
    'subject_area',
    'subject_level',
    'Subject',
    'UKPRN',
]
