stages:
  prep-wy:
    cmd: PYTHONPATH=site/_pipelines python site/_pipelines/ks4/prepare.py wycc
    wdir: ../../..
    deps:
      - site/_pipelines/ks4/prepare.py
      - data/csv/ks4/Key stage 4 performance.csv
    outs:
      - site/wycc/supply/ks4/_data/stats.csv:
          cache: false
      - site/wycc/supply/ks4/_data/summary.json:
          cache: false
