stages:
  metadata:
    cmd: PYTHONPATH=site/_pipelines python site/_pipelines/datacity/prepare.py wycc
    wdir: ../../..
    deps:
      - site/_pipelines/datacity/prepare.py
      - site/_pipelines/datacity/soc4.py
      - site/_pipelines/lookups.py
      - data/csv/datacity/JobPostingsBySOC4Code.csv
    outs:
      - site/wycc/demand/_data/postings_by_soc4_unit.csv:
          cache: false