stages:
  prep-wy:
    cmd: PYTHONPATH=site/_pipelines python site/_pipelines/nomis/prepare.py wycc
    wdir: ../../..
    deps:
      - site/_pipelines/nomis/prepare.py
      - data/csv/nomis/ukbc-lu-emp.csv
      - data/csv/nomis/bres.csv
    outs:
      - site/wycc/demand/nomis/_data/size_over_time_whole_region.csv:
          cache: false
      - site/wycc/demand/nomis/_data/industry_sector_latest_year.csv:
          cache: false
      - site/wycc/demand/nomis/_data/size_time_pct_change.csv:
          cache: false
      - site/wycc/demand/nomis/_data/headline_stats.json:
          cache: false
      - site/wycc/demand/nomis/_data/stats.json:
          cache: false

  prep-ny:
    cmd: PYTHONPATH=site/_pipelines python site/_pipelines/nomis/prepare.py nycc
    wdir: ../../..
    deps:
      - site/_pipelines/nomis/prepare.py
      - data/csv/nomis/ukbc-lu-emp.csv
      - data/csv/nomis/bres.csv
    outs:
      - site/nycc/demand/nomis/_data/size_over_time_whole_region.csv:
          cache: false
      - site/nycc/demand/nomis/_data/industry_sector_latest_year.csv:
          cache: false
      - site/nycc/demand/nomis/_data/size_time_pct_change.csv:
          cache: false
      - site/nycc/demand/nomis/_data/headline_stats.json:
          cache: false
      - site/nycc/demand/nomis/_data/stats.json:
          cache: false
